//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_chat.UsersService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="users", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class users : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Connection_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsOnlineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int User_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ASP_chat.UsersService.chats[] chatsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ASP_chat.UsersService.chats[] chats1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ASP_chat.UsersService.messages[] messagesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Connection_Id {
            get {
                return this.Connection_IdField;
            }
            set {
                if ((object.ReferenceEquals(this.Connection_IdField, value) != true)) {
                    this.Connection_IdField = value;
                    this.RaisePropertyChanged("Connection_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsOnline {
            get {
                return this.IsOnlineField;
            }
            set {
                if ((this.IsOnlineField.Equals(value) != true)) {
                    this.IsOnlineField = value;
                    this.RaisePropertyChanged("IsOnline");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int User_ID {
            get {
                return this.User_IDField;
            }
            set {
                if ((this.User_IDField.Equals(value) != true)) {
                    this.User_IDField = value;
                    this.RaisePropertyChanged("User_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ASP_chat.UsersService.chats[] chats {
            get {
                return this.chatsField;
            }
            set {
                if ((object.ReferenceEquals(this.chatsField, value) != true)) {
                    this.chatsField = value;
                    this.RaisePropertyChanged("chats");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ASP_chat.UsersService.chats[] chats1 {
            get {
                return this.chats1Field;
            }
            set {
                if ((object.ReferenceEquals(this.chats1Field, value) != true)) {
                    this.chats1Field = value;
                    this.RaisePropertyChanged("chats1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ASP_chat.UsersService.messages[] messages {
            get {
                return this.messagesField;
            }
            set {
                if ((object.ReferenceEquals(this.messagesField, value) != true)) {
                    this.messagesField = value;
                    this.RaisePropertyChanged("messages");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="chats", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class chats : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Chat_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int User_1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int User_2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ASP_chat.UsersService.messages[] messagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ASP_chat.UsersService.users usersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ASP_chat.UsersService.users users1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Chat_ID {
            get {
                return this.Chat_IDField;
            }
            set {
                if ((this.Chat_IDField.Equals(value) != true)) {
                    this.Chat_IDField = value;
                    this.RaisePropertyChanged("Chat_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int User_1 {
            get {
                return this.User_1Field;
            }
            set {
                if ((this.User_1Field.Equals(value) != true)) {
                    this.User_1Field = value;
                    this.RaisePropertyChanged("User_1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int User_2 {
            get {
                return this.User_2Field;
            }
            set {
                if ((this.User_2Field.Equals(value) != true)) {
                    this.User_2Field = value;
                    this.RaisePropertyChanged("User_2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ASP_chat.UsersService.messages[] messages {
            get {
                return this.messagesField;
            }
            set {
                if ((object.ReferenceEquals(this.messagesField, value) != true)) {
                    this.messagesField = value;
                    this.RaisePropertyChanged("messages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ASP_chat.UsersService.users users {
            get {
                return this.usersField;
            }
            set {
                if ((object.ReferenceEquals(this.usersField, value) != true)) {
                    this.usersField = value;
                    this.RaisePropertyChanged("users");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ASP_chat.UsersService.users users1 {
            get {
                return this.users1Field;
            }
            set {
                if ((object.ReferenceEquals(this.users1Field, value) != true)) {
                    this.users1Field = value;
                    this.RaisePropertyChanged("users1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="messages", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class messages : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Chat_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int From_UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsReadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Message_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Send_DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ASP_chat.UsersService.chats chatsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ASP_chat.UsersService.users usersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Chat_ID {
            get {
                return this.Chat_IDField;
            }
            set {
                if ((this.Chat_IDField.Equals(value) != true)) {
                    this.Chat_IDField = value;
                    this.RaisePropertyChanged("Chat_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int From_User {
            get {
                return this.From_UserField;
            }
            set {
                if ((this.From_UserField.Equals(value) != true)) {
                    this.From_UserField = value;
                    this.RaisePropertyChanged("From_User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsRead {
            get {
                return this.IsReadField;
            }
            set {
                if ((this.IsReadField.Equals(value) != true)) {
                    this.IsReadField = value;
                    this.RaisePropertyChanged("IsRead");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Message_ID {
            get {
                return this.Message_IDField;
            }
            set {
                if ((this.Message_IDField.Equals(value) != true)) {
                    this.Message_IDField = value;
                    this.RaisePropertyChanged("Message_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Send_Date {
            get {
                return this.Send_DateField;
            }
            set {
                if ((this.Send_DateField.Equals(value) != true)) {
                    this.Send_DateField = value;
                    this.RaisePropertyChanged("Send_Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ASP_chat.UsersService.chats chats {
            get {
                return this.chatsField;
            }
            set {
                if ((object.ReferenceEquals(this.chatsField, value) != true)) {
                    this.chatsField = value;
                    this.RaisePropertyChanged("chats");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ASP_chat.UsersService.users users {
            get {
                return this.usersField;
            }
            set {
                if ((object.ReferenceEquals(this.usersField, value) != true)) {
                    this.usersField = value;
                    this.RaisePropertyChanged("users");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UsersService.IUsers")]
    public interface IUsers {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsers/GetAllUsers", ReplyAction="http://tempuri.org/IUsers/GetAllUsersResponse")]
        ASP_chat.UsersService.users[] GetAllUsers(int mainUserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsers/GetAllUsers", ReplyAction="http://tempuri.org/IUsers/GetAllUsersResponse")]
        System.Threading.Tasks.Task<ASP_chat.UsersService.users[]> GetAllUsersAsync(int mainUserID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUsersChannel : ASP_chat.UsersService.IUsers, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsersClient : System.ServiceModel.ClientBase<ASP_chat.UsersService.IUsers>, ASP_chat.UsersService.IUsers {
        
        public UsersClient() {
        }
        
        public UsersClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsersClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsersClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsersClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ASP_chat.UsersService.users[] GetAllUsers(int mainUserID) {
            return base.Channel.GetAllUsers(mainUserID);
        }
        
        public System.Threading.Tasks.Task<ASP_chat.UsersService.users[]> GetAllUsersAsync(int mainUserID) {
            return base.Channel.GetAllUsersAsync(mainUserID);
        }
    }
}
