//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_chat.WcfService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="users", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class users : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Connection_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsOnlineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int User_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ASP_chat.WcfService.chats[] chatsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ASP_chat.WcfService.chats[] chats1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ASP_chat.WcfService.groups_users[] groups_usersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ASP_chat.WcfService.messages[] messagesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Connection_Id {
            get {
                return this.Connection_IdField;
            }
            set {
                if ((object.ReferenceEquals(this.Connection_IdField, value) != true)) {
                    this.Connection_IdField = value;
                    this.RaisePropertyChanged("Connection_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsOnline {
            get {
                return this.IsOnlineField;
            }
            set {
                if ((this.IsOnlineField.Equals(value) != true)) {
                    this.IsOnlineField = value;
                    this.RaisePropertyChanged("IsOnline");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int User_ID {
            get {
                return this.User_IDField;
            }
            set {
                if ((this.User_IDField.Equals(value) != true)) {
                    this.User_IDField = value;
                    this.RaisePropertyChanged("User_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ASP_chat.WcfService.chats[] chats {
            get {
                return this.chatsField;
            }
            set {
                if ((object.ReferenceEquals(this.chatsField, value) != true)) {
                    this.chatsField = value;
                    this.RaisePropertyChanged("chats");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ASP_chat.WcfService.chats[] chats1 {
            get {
                return this.chats1Field;
            }
            set {
                if ((object.ReferenceEquals(this.chats1Field, value) != true)) {
                    this.chats1Field = value;
                    this.RaisePropertyChanged("chats1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ASP_chat.WcfService.groups_users[] groups_users {
            get {
                return this.groups_usersField;
            }
            set {
                if ((object.ReferenceEquals(this.groups_usersField, value) != true)) {
                    this.groups_usersField = value;
                    this.RaisePropertyChanged("groups_users");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ASP_chat.WcfService.messages[] messages {
            get {
                return this.messagesField;
            }
            set {
                if ((object.ReferenceEquals(this.messagesField, value) != true)) {
                    this.messagesField = value;
                    this.RaisePropertyChanged("messages");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="chats", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class chats : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Chat_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int User_1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int User_2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ASP_chat.WcfService.messages[] messagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ASP_chat.WcfService.users usersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ASP_chat.WcfService.users users1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Chat_ID {
            get {
                return this.Chat_IDField;
            }
            set {
                if ((this.Chat_IDField.Equals(value) != true)) {
                    this.Chat_IDField = value;
                    this.RaisePropertyChanged("Chat_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int User_1 {
            get {
                return this.User_1Field;
            }
            set {
                if ((this.User_1Field.Equals(value) != true)) {
                    this.User_1Field = value;
                    this.RaisePropertyChanged("User_1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int User_2 {
            get {
                return this.User_2Field;
            }
            set {
                if ((this.User_2Field.Equals(value) != true)) {
                    this.User_2Field = value;
                    this.RaisePropertyChanged("User_2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ASP_chat.WcfService.messages[] messages {
            get {
                return this.messagesField;
            }
            set {
                if ((object.ReferenceEquals(this.messagesField, value) != true)) {
                    this.messagesField = value;
                    this.RaisePropertyChanged("messages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ASP_chat.WcfService.users users {
            get {
                return this.usersField;
            }
            set {
                if ((object.ReferenceEquals(this.usersField, value) != true)) {
                    this.usersField = value;
                    this.RaisePropertyChanged("users");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ASP_chat.WcfService.users users1 {
            get {
                return this.users1Field;
            }
            set {
                if ((object.ReferenceEquals(this.users1Field, value) != true)) {
                    this.users1Field = value;
                    this.RaisePropertyChanged("users1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="groups_users", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class groups_users : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Group_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Groups_Users_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int User_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ASP_chat.WcfService.groups groupsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ASP_chat.WcfService.users usersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Group_ID {
            get {
                return this.Group_IDField;
            }
            set {
                if ((this.Group_IDField.Equals(value) != true)) {
                    this.Group_IDField = value;
                    this.RaisePropertyChanged("Group_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Groups_Users_ID {
            get {
                return this.Groups_Users_IDField;
            }
            set {
                if ((this.Groups_Users_IDField.Equals(value) != true)) {
                    this.Groups_Users_IDField = value;
                    this.RaisePropertyChanged("Groups_Users_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int User_ID {
            get {
                return this.User_IDField;
            }
            set {
                if ((this.User_IDField.Equals(value) != true)) {
                    this.User_IDField = value;
                    this.RaisePropertyChanged("User_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ASP_chat.WcfService.groups groups {
            get {
                return this.groupsField;
            }
            set {
                if ((object.ReferenceEquals(this.groupsField, value) != true)) {
                    this.groupsField = value;
                    this.RaisePropertyChanged("groups");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ASP_chat.WcfService.users users {
            get {
                return this.usersField;
            }
            set {
                if ((object.ReferenceEquals(this.usersField, value) != true)) {
                    this.usersField = value;
                    this.RaisePropertyChanged("users");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="messages", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class messages : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Chat_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int From_UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string From_UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Group_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsReadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Message_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Send_DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ASP_chat.WcfService.chats chatsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ASP_chat.WcfService.groups groupsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ASP_chat.WcfService.users usersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Chat_ID {
            get {
                return this.Chat_IDField;
            }
            set {
                if ((this.Chat_IDField.Equals(value) != true)) {
                    this.Chat_IDField = value;
                    this.RaisePropertyChanged("Chat_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int From_User {
            get {
                return this.From_UserField;
            }
            set {
                if ((this.From_UserField.Equals(value) != true)) {
                    this.From_UserField = value;
                    this.RaisePropertyChanged("From_User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string From_UserName {
            get {
                return this.From_UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.From_UserNameField, value) != true)) {
                    this.From_UserNameField = value;
                    this.RaisePropertyChanged("From_UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Group_ID {
            get {
                return this.Group_IDField;
            }
            set {
                if ((this.Group_IDField.Equals(value) != true)) {
                    this.Group_IDField = value;
                    this.RaisePropertyChanged("Group_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsRead {
            get {
                return this.IsReadField;
            }
            set {
                if ((this.IsReadField.Equals(value) != true)) {
                    this.IsReadField = value;
                    this.RaisePropertyChanged("IsRead");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Message_ID {
            get {
                return this.Message_IDField;
            }
            set {
                if ((this.Message_IDField.Equals(value) != true)) {
                    this.Message_IDField = value;
                    this.RaisePropertyChanged("Message_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Send_Date {
            get {
                return this.Send_DateField;
            }
            set {
                if ((this.Send_DateField.Equals(value) != true)) {
                    this.Send_DateField = value;
                    this.RaisePropertyChanged("Send_Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ASP_chat.WcfService.chats chats {
            get {
                return this.chatsField;
            }
            set {
                if ((object.ReferenceEquals(this.chatsField, value) != true)) {
                    this.chatsField = value;
                    this.RaisePropertyChanged("chats");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ASP_chat.WcfService.groups groups {
            get {
                return this.groupsField;
            }
            set {
                if ((object.ReferenceEquals(this.groupsField, value) != true)) {
                    this.groupsField = value;
                    this.RaisePropertyChanged("groups");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ASP_chat.WcfService.users users {
            get {
                return this.usersField;
            }
            set {
                if ((object.ReferenceEquals(this.usersField, value) != true)) {
                    this.usersField = value;
                    this.RaisePropertyChanged("users");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="groups", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class groups : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Group_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Group_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ASP_chat.WcfService.groups_users[] groups_usersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ASP_chat.WcfService.messages[] messagesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Group_ID {
            get {
                return this.Group_IDField;
            }
            set {
                if ((this.Group_IDField.Equals(value) != true)) {
                    this.Group_IDField = value;
                    this.RaisePropertyChanged("Group_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Group_Name {
            get {
                return this.Group_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Group_NameField, value) != true)) {
                    this.Group_NameField = value;
                    this.RaisePropertyChanged("Group_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ASP_chat.WcfService.groups_users[] groups_users {
            get {
                return this.groups_usersField;
            }
            set {
                if ((object.ReferenceEquals(this.groups_usersField, value) != true)) {
                    this.groups_usersField = value;
                    this.RaisePropertyChanged("groups_users");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ASP_chat.WcfService.messages[] messages {
            get {
                return this.messagesField;
            }
            set {
                if ((object.ReferenceEquals(this.messagesField, value) != true)) {
                    this.messagesField = value;
                    this.RaisePropertyChanged("messages");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceError", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class ServiceError : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfService.IAuth")]
    public interface IAuth {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuth/Registration", ReplyAction="http://tempuri.org/IAuth/RegistrationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ASP_chat.WcfService.ServiceError), Action="http://tempuri.org/IAuth/RegistrationServiceErrorFault", Name="ServiceError", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
        ASP_chat.WcfService.users Registration(ASP_chat.WcfService.users user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuth/Registration", ReplyAction="http://tempuri.org/IAuth/RegistrationResponse")]
        System.Threading.Tasks.Task<ASP_chat.WcfService.users> RegistrationAsync(ASP_chat.WcfService.users user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuth/Login", ReplyAction="http://tempuri.org/IAuth/LoginResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ASP_chat.WcfService.ServiceError), Action="http://tempuri.org/IAuth/LoginServiceErrorFault", Name="ServiceError", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
        ASP_chat.WcfService.users Login(ASP_chat.WcfService.users user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuth/Login", ReplyAction="http://tempuri.org/IAuth/LoginResponse")]
        System.Threading.Tasks.Task<ASP_chat.WcfService.users> LoginAsync(ASP_chat.WcfService.users user);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAuthChannel : ASP_chat.WcfService.IAuth, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthClient : System.ServiceModel.ClientBase<ASP_chat.WcfService.IAuth>, ASP_chat.WcfService.IAuth {
        
        public AuthClient() {
        }
        
        public AuthClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ASP_chat.WcfService.users Registration(ASP_chat.WcfService.users user) {
            return base.Channel.Registration(user);
        }
        
        public System.Threading.Tasks.Task<ASP_chat.WcfService.users> RegistrationAsync(ASP_chat.WcfService.users user) {
            return base.Channel.RegistrationAsync(user);
        }
        
        public ASP_chat.WcfService.users Login(ASP_chat.WcfService.users user) {
            return base.Channel.Login(user);
        }
        
        public System.Threading.Tasks.Task<ASP_chat.WcfService.users> LoginAsync(ASP_chat.WcfService.users user) {
            return base.Channel.LoginAsync(user);
        }
    }
}
